### ISSUE TITLE
About using distributed training.

### ISSUE THREAD

**Issue by anonymoustbd** [sconlyshootery/FeatDepth#20]

**Comment by anonymoustbd** [comment]
I am confused about using distributed training. I have 4 gpus, it works only when i set '--nproc_per_node=1', '--gpus defalt=0 or 1 or 2 or 3', and 'IMGS_PER_GPU = 1'. How should i perform the setting to properly utilize all gpus? Thanks a lot!

**Comment by anonymoustbd** [comment]
> _No description provided._

**Comment by sconlyshootery** [comment]
For your situation, you only need to set 'nproc_per_node' and 'IMGS_PER_GPU', 'gpus default' is not needed, since it is only applicable to non-distributed training. When you set '--nproc_per_node=4', you will use all your gpus. The setting 'IMGS_PER_GPU' depends on your GPU memories, you can set more when your memory is large. It can be set to around 3 if you have 12 GB GPU memories.

**Comment by anonymoustbd** [comment]
Thanks for your reply. However, some errors occurred when I set '--nproc_per_node=8' and 'IMGS_PER_GPU=1' (8 2080ti gpus).  Errors:
'''
RuntimeError: all tensors must be on devices[0]

RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/test/unsupervised_learning/featdepth_4x_8ka/mono/model/mono_fm/net.py", line 47, in forward
    loss_dict = self.compute_losses(inputs, outputs)
  File "/test/unsupervised_learning/featdepth_4x_8ka/mono/model/mono_fm/net.py", line 80, in compute_losses
    outputs = self.generate_images_pred(inputs, outputs, scale)
  File "/test/unsupervised_learning/featdepth_4x_8ka/mono/model/mono_fm/net.py", line 162, in generate_images_pred
    cam_points = self.backproject(depth, inputs[("inv_K")])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/test/unsupervised_learning/featdepth_4x_8ka/mono/model/mono_fm/layers.py", line 58, in forward
    cam_points = torch.matmul(inv_K[:, :3, :3], self.pix_coords.cuda())
RuntimeError: The size of tensor a (3) must match the size of tensor b (20) at non-singleton dimension 0

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/bin/python', '-u', 'train.py', '--local_rank=7']' returned non-zero exit status 1.
'''

**Comment by sconlyshootery** [comment]
It seems weird that the size of dimension 0 of inv_k is 3 and that of pix_coords is 20, which is supposed to be the same with IMGS_PER_GPU. I advise you enter debug mode to track the reason why the size of inv_k and pix_coords become such numbers.

**Comment by youzunzhi** [comment]
@sconlyshootery 
Hi, I have encountered a similar problem:
> Original Traceback (most recent call last):
  File "/home/youzunzhi/anaconda3/envs/featdepth/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/youzunzhi/anaconda3/envs/featdepth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/youzunzhi/featdepth-my/mono/model/mono_fm/net.py", line 49, in forward
    loss_dict = self.compute_losses(inputs, outputs)
  File "/home/youzunzhi/featdepth-my/mono/model/mono_fm/net.py", line 82, in compute_losses
    outputs = self.generate_images_pred(inputs, outputs, scale)
  File "/home/youzunzhi/featdepth-my/mono/model/mono_fm/net.py", line 164, in generate_images_pred
    cam_points = self.backproject(depth, inputs[("inv_K")])
  File "/home/youzunzhi/anaconda3/envs/featdepth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/youzunzhi/featdepth-my/mono/model/mono_fm/layers.py", line 63, in forward
    cam_points = depth.view(self.batch_size, 1, -1) * cam_points
RuntimeError: The size of tensor a (163840) must match the size of tensor b (327680) at non-singleton dimension 2

I am using distributed training with 2 GPUs (--nproc_per_node=2), and IMGS_PER_GPU = 2.
The sizes of inv_k and self.pix_coords in Backproject.forward() are [1, 4, 4] and [2, 3, 327680], respectively. Therefore cam_points's size is [2, 3, 327680], but depth's size is [1, 1, 320, 1024], causing the RuntimeError. I tried to track the size of inv_k. In the `batch_processor()` function, before it is passed to the model, `data["inv_K"]`'s size is [2, 4, 4]. Since the model is a MMDistributedDataParallel, it becomes [1, 4, 4] when passed to the model. So should the size of `data["inv_K"]` be [4,4,4] in `batch_processor()`? How should I do to correct the error? Thanks a lot!!
