### ISSUE TITLE
ImportError: cannot import name 'get_world_size'

### ISSUE THREAD

**Issue by wurongyuan** [sconlyshootery/FeatDepth#41]
run infer.py and get error

**Comment by wurongyuan** [comment]
Traceback (most recent call last):
  File "D:/PycharmProject/depth_estimate_2/scripts/infer.py", line 16, in <module>
    from mono.datasets.utils import readlines
  File "D:\PycharmProject\depth_estimate_2\mono\datasets\__init__.py", line 1, in <module>
    from .loader import build_dataloader
  File "D:\PycharmProject\depth_estimate_2\mono\datasets\loader\__init__.py", line 5, in <module>
    from .build_loader import build_dataloader
  File "D:\PycharmProject\depth_estimate_2\mono\datasets\loader\build_loader.py", line 10, in <module>
    from .sampler import GroupSampler, DistributedGroupSampler, DistributedSampler
  File "D:\PycharmProject\depth_estimate_2\mono\datasets\loader\sampler.py", line 11, in <module>
    from torch.distributed import get_world_size, get_rank
ImportError: cannot import name 'get_world_size'

**Comment by sconlyshootery** [comment]
It seems that your torch isn't installed correctly or you didn't install the GPU version.

**Comment by sconlyshootery** [comment]
I will close this issue, if you have further question, you are welcome to reopen it.
