### ISSUE TITLE
CUDA capability sm_86 is not compatible with the current PyTorch installation.

### ISSUE THREAD

**Issue by ghost** [sconlyshootery/FeatDepth#68]
When I follow the install in the README out of the box and try to run `infer.py` I get the following error:

```
UserWarning: 
NVIDIA GeForce RTX 3060 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "./infer.py", line 76, in <module>
    evaluate(cfg_path, model_path, img_path, output_path)
  File "./infer.py", line 63, in evaluate
    depth, disp_resized = predict(cv2_img, model)
  File "./infer.py", line 34, in predict
    im_tensor = transform(cv2_img)
  File "./infer.py", line 27, in transform
    im_tensor = im_tensor.permute(0, 3, 1, 2).contiguous()
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

I managed to solve this by running ` conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia` which I got from https://pytorch.org/get-started/locally/. I am posting this here to help anyone debug the issue quickly and maybe so the compatibility can be rectified out of the box.

Thanks and cheers!

**Comment by sconlyshootery** [comment]
Thank you for your contribution!

**Comment by ghost** [comment]
@sconlyshootery how did you fix this?

**Comment by sconlyshootery** [comment]
I haven't met this problem, since my CUDA capability is lower. Based on the information you provide, I think updating cuda version and pytorch version is the best way to solve it.
