### ISSUE TITLE
running infer_singleimage.py in win10 ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by masommao** [sconlyshootery/FeatDepth#71]
Traceback (most recent call last):
  File "D:/workspace/monodepth/FeatDepth/scripts/infer_singleimage.py", line 15, in <module>
    from mono.datasets.utils import readlines
  File "D:\workspace\monodepth\FeatDepth\mono\datasets\__init__.py", line 1, in <module>
    from .loader import build_dataloader
  File "D:\workspace\monodepth\FeatDepth\mono\datasets\loader\__init__.py", line 5, in <module>
    from .build_loader import build_dataloader
  File "D:\workspace\monodepth\FeatDepth\mono\datasets\loader\build_loader.py", line 13, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

**Comment by sconlyshootery** [comment]
You can try not to import resource, remove corresponding 3 lines starting from below:
https://github.com/sconlyshootery/FeatDepth/blob/550420b3fb51a027549716b74c6fbce41651d3a5/mono/datasets/loader/build_loader.py#L13
